language: php

php:
    # We only specify one version so we only get one worker
    - 5.4

notifications:
    email: false

env:
    - REPORT_EXIT_STATUS=1

global:
  - REPO="git@github.com:mylops/https://github.com/mylops/mylops.git"
  
